language: node_js
node_js:
  - "16"
sudo: required
services:
  - docker
script:
  - docker build -t $imagename .
after_success:
  - docker -D login $docker_registry_url -u $DOCKER_USER -p $DOCKER_PASSWORD 
  - docker tag $imagename $docker_registry_url/$imagename:$TRAVIS_BUILD_NUMBER
  - docker push $docker_registry_url/$imagename:$TRAVIS_BUILD_NUMBER
