language: node_js
node_js:
  - "16"
sudo: required
services:
  - docker
script:
  - docker build -t ui-advisor .
after_success:
  - docker -D login $docker_registry_url -u $DOCKER_USER -p $DOCKER_PASSWORD 
  - docker tag ui-advisor $docker_registry_url/ui-advisor:$TRAVIS_BUILD_NUMBER
  - docker push $docker_registry_url/ui-advisor:$TRAVIS_BUILD_NUMBER
